### ISSUE TITLE
Mime type association problem

### ISSUE THREAD

**Issue by prandazzo** [wkt/file-roller-osx#1]
I'm using OSX Sierra.

When I'm trying to open a file directly from file roller a popup says that there are no applications associated with that file type.

Tried some type of files without success.
<img width="643" alt="schermata 2016-11-10 alle 15 26 14" src="https://cloud.githubusercontent.com/assets/557245/20180259/10653944-a75a-11e6-8c8b-325d30cc3198.png">

**Comment by wkt** [comment]
Noticed!
I will try to fix it,Thank you!

**Comment by wkt** [comment]
fixed
